config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #devise_for :customers
  root to: 'homes#top'
  get '/search', to: 'searchs#search'
  
  resources :customers, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :items, only: [:index, :show, :create, :edit, :update, :destroy] do
   resources :posts, only: [:create, :destroy] do
     resource :favorites, only: [:create, :destroy]
   end
  end
  resources :genres, only: [:index, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attachment :image
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  
  attachment :image
  belongs_to :genre, optional: true
  has_many :post, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :item
  belongs_to :user
  validates :body, presence: true, length: {maximum: 80}
   has_many :favorites, dependent: :destroy
  
  def favorited_by?(current_user, post_id)
   favorites.where(post_id: post_id,user_id: current_user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :post, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    customers_path # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @customers = Customer.all
    @customers = Customer.page(params[:page]).per(5)
    @customer = Customer.new
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.new(customer_params)
   if @customer.save
     redirect_to customers_path(@customer), notice: "投稿成功しました"
   else
     @customers = Customer.all
     render 'index'
   end
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to customer_path(@customer.id)
  end
  
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to customers_path
  end
  
 private
 def customer_params
  params.require(:customer).permit(:last_name, :first_name, :image)
 end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    @item = Item.find(params[:item_id])
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save

  end
  
  def destroy
    @item = Item.find(params[:item_id])
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
  
  end
  
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @genres =  Genre.all
    @genres = Genre.page(params[:page]).per(5)
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
    redirect_to genres_path
    else
     render 'index'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
     redirect_to genres_path
    else
     render 'edit'
    end
  end
  
  def destroy
    @genres = Genre.find(params[:id])
    @genres.destroy
    redirect_to genres_path
  end
  
  private
 def genre_params
  params.require(:genre).permit(:name)
 end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @items = Item.all
    @items = Item.page(params[:page]).per(5)
    @item = Item.new 
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])
    #@customers = Customer.find(params[:id])
    @post = Post.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
     redirect_to item_path(@item), notice: "投稿成功しました"
    else
     @items = Item.all
     render 'index'
    end
  end
  
  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to item_path
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end
  
  private
   def item_params
    params.require(:item).permit(:name, :describe, :jan_code, :image, :genre_id)
   end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def create
    item = Item.find(params[:item_id])
    comment = current_user.post.new(post_params)
    comment.item_id = item.id
    comment.save
    redirect_to item_path(item)
  end  

  def destroy
    Post.find_by(id: params[:id], item_id: params[:item_id]).destroy
    redirect_to item_path(params[:item_id])
  end
  
 private
 def post_params
  params.require(:post).permit(:body)
 end
 
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
 
  def search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    @records = search_for(@model, @content, @method)
  end

private
 def search_for(model, content, method)
   if model == 'item'
    if method == 'perfect'
     Item.where(name: content)
    else
     Item.where('name LIKE ?', '%'+content+'%')
    end
   elsif model == 'genre'
     if method == 'perfect'
      Genre.where(name: content)
     else
      Genre.where('name LIKE ?', '%'+content+'%')
     end
   end
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/customers/edit,.html.erb
  
<div class="container-fluid col-lg-10">
 <div class="row">
  <div class="col-md-3 mb-3">
  </div>
 </div>
  <h1>会員情報登録</h1>
  <%= form_with model:@customer, local:true dp |f| %>
  <tbody>
   <tr>
    <th>氏名</th>
    <td><%= f.text_field :last_name, autofocus: true, id:"inputName", placeholder:"田中" %></td>
    <td><%= f.text_field :first_name, autofocus: true, id:"inputName", placeholder:"太郎" %></td>
   </tr>
  </tbody>
  <div class="row">
   <div class="col-md-4 offset-md-4">
    <%= f.submit "内容を保存", class:'btn btn-success' %>
    <% end %>
   </div>
  </div>
</div>

app/views/customers/edit.html.erb
<%= render 'layouts/header' %>
<div class="container-fluid col-lg-10">
 <div class="row">
  <div class="col-md-10 mb-3">
  <h1>会員情報登録</h1>
  <%= form_with model: @customer, local:true do |f| %>
 <table class='table table-hover table-inverse'>
  <thead>
  <tr>
  　<th>会員画像</th>
  　<th>会員名（姓）</th>
  　<th>会員名（名）</th>
  </tr>
  </thead>
  
  <tbody>
   <tr>
    <td><%= f.attachment_field :image %></td>
    <td><%= f.text_field :last_name, autofocus: true, id:"inputName", placeholder:"田中" %></td>
    <td><%= f.text_field :first_name, autofocus: true, id:"inputName", placeholder:"太郎" %></td>
   </tr>
  </tbody>
   <tr>
    <td><%= f.submit "変更を保存", class:'btn btn-success' %></td>
   </tr> 
 </table>
    <% end %>
   </div>
  </div>
</div>
 <%= render 'layouts/footer' %>

app/views/customers/index.html.erb
 <%= render 'layouts/header' %>
 <div class="container-fluid col-lg-10">
 <div class="row">
  <div class="col-md-3 mb-3">
  </div>
 </div>
  <h1>会員一覧</h1>
  
 <table class='table table-hover table-inverse'>
  <thead>
    <tr>
    <th>会員画像</th>
    <th>会員名（姓）</th>
    <th>会員名（名）</th>
    <th></th>
    <th></th>
    </tr>
  </thead>
  <% @customers.each do |customer| %>
  <tbody>
   <tr>
     <td><%= attachment_image_tag customer, :image, :fill, 100, 100, format: 'jpeg' %></td>
     <td><%= customer.last_name %></td>
     <td><%= customer.first_name %></td>
     <td><%= link_to "会員詳細", customer_path(customer), class:'btn btn-primary' %></td>
   </tr>
  <% end %>
  </tbody> 
 </table>
  <%= form_with model: @customer, local: true do |f| %>
  <table class= 'table'>
  <h3>会員新規登録</h3>
  <tbody>
   <tr>
    <th>会員画像</th>
    <td><%= f.attachment_field :image %></td>
   </tr>
   <tr>
    <th>氏名</th>
    <td><%= f.text_field :last_name, autofocus: true, id:"inputName", placeholder:"田中" %></td>
    <td><%= f.text_field :first_name, autofocus: true, id:"inputName", placeholder:"太郎" %></td>
   </tr>
    <td><%= f.submit "新規登録", class:'btn btn-success' %></td>
    <% end %>
    <tr><td><%= paginate @customers %></td></tr>
  </tbody>
  </table>
</div>
<%= render 'layouts/footer' %>

app/views/customers/show.html.erb
<%= render 'layouts/header' %>
 <div class="container-fluid col-lg-10">
 <div class="row">
  <div class="col-md-3 mb-3">
  </div>
 </div>
  <h1>会員詳細</h1>
  <table class='table table-hover table-inverse'>
  <thead>
    <tr>
    <th>会員画像</th>
    <th>会員名（姓）</th>
    <th>会員名（名）</th>
    <th></th>
    <th></th>
    </tr>
  </thead>
  <tbody>
   <tr>
     <th><%= attachment_image_tag @customer, :image, :fill, 100, 100, format: 'jpeg' %></th>
     <th><%= @customer.last_name %></th>
     <th><%= @customer.first_name %></th>
     <th><%= link_to '登録情報を編集する', edit_customer_path(@customer), class:'btn btn-success'%></th>
     <th><%= link_to '退会する', customer_path(@customer),method: :delete, "data-confirm" => "本当に退会してもよろしいでしょうか？", class:'btn btn-danger' %></th>
   </tr>
  </tbody>
  </table>
</div>
 <%= render 'layouts/footer' %>
 

app/views/favorites/_favorite.html.erb
<div id="favorites_buttons_<%= post.id %>">
<% if post.favorited_by?(current_user, post.id) %>
   <%= link_to item_post_favorites_path(@item.id, post.id), method: :delete, remote: true do %>
    ♥<%= post.favorites.count %>いいね
   <% end %>
   
   <% else %>
   <%= link_to item_post_favorites_path(@item.id, post.id), method: :post, remote: true do %>
    ♡<%= post.favorites.count %>いいね
   <% end %>
  <% end %>
  </div>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @post.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {post: @post}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @post.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {post: @post}) %>");

app/views/genres/edit.html.erb
<%= render 'layouts/header' %>
<div class="container text-center center-block">
 <div class="row offset-0">
  <div class="mx-auto">
   <br>
   <h1>ジャンル編集</h1>
   <%= form_with model: @genre, local: true do |f| %>
    <%= f.label :name, "ジャンル名" %>
    <%= f.text_field :name, placeholder: "ジャンル名" %>
    <%= f.submit '変更を保存する', class: 'btn btn-success' %>
   <% end %>
   <br>
  </div>
 </div>
</div>
<%= render 'layouts/footer' %>

app/views/genres/index.html.erb
<%= render 'layouts/header' %>
<div class="container text-center center-block">
 
 <div class="row offset-0">
  <div class="mx-auto">
   </br></br>
   <h1>ジャンル一覧・追加</h1>  
   <%= form_with model:@genre, local: true do |f| %>
    <%= f.label :name, "ジャンル名" %>
    <%= f.text_field :name, placeholder: "ジャンル名" %>
    <%= f.submit '新規登録', class: 'btn btn-success' %>
   <% end %>
   </br></br>
  </div>
  <table class='table table-hover table-inverse'>
   <thead>
    <tr>
      <th>ジャンル名</th>
      <th></th>
      <th></th>
    </tr> 
   </thead>
   <tbody>
     <% @genres.each do |genre| %>
     <tr>
       <td><%= genre.name %></td>
       <td><%= link_to "編集する", edit_genre_path(genre), class:"btn btn-primary" %></td>
       <td><%= link_to "削除する", genre_path(genre),method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn btn-danger" %></td>
     </tr>
     <% end %>
     <tr><td><%= paginate @genres %></td></tr>
   </tbody>
  </table>
 </div>
</div>
<%= render 'layouts/footer' %>

app/views/items/_comment.erb
<div class="posts">
  <table class='table table-hover table-inverse'>
   <thead>
  <th>投稿者</th>
  <th>投稿タイトル</th>
  <th>投稿文</th>
  <th>いいね</th>
   </thead>
   <tbody>
  <% @item.posts.each do |post| %>
   <td><%= post.customer.name %></td>
   <td><%= post.created_at.strftime('%Y/%m/%d') %></td>
   <td><%= post.title %></td>
   <td><%= post.body %></td>
   <% if post_comment.user == current_user %>
   <%= link_to "削除", item_post_path(post.item, post), method: :delete %>
   <% end %>
   <% if @item.favorited_by?(current_user) %>
   <td><%= link_to item_favorites_path(@item), method: :delete do %>
    ♥<%= @item.favorites.count %>いいね
   <% end %>
   </td>
   <% else %>
   <td><%= link_to item_favorites_path(@item), method: :post do %>
    ♡<%= @item.favorites.count %>いいね
   <% end %>
   </td>
  <% end %>
  <% end %>
 </div>
 <div class="new-post">
  <%= form_with(model:[@item,@post], local: true) do |f| %>
   <%= f.text_field :title %>
   <%= f.text_area :body, rows="5" %>
   <%= f.submit '投稿する', class:'btn btn-success' %>
  <% end %>
  </tbody>
 </table>
 </div>
</div>

app/views/items/_comments.erb
<div class="posts">
 
  <th>投稿者</th>
  <th>投稿タイトル</th>
  <th>投稿文</th>
  <th>いいね</th>
  <% @item.posts.each do |post| %>
   <td><%= post.customer.name %></td>
   <td><%= post.created_at.strftime('%Y/%m/%d') %></td>
   <td><%= post.title %></td>
   <td><%= post.body %></td>
   <% if post_comment.customer == current_customer %>
   <%= link_to "削除", item_post_path(post.item, post), method: :delete %>
   <% end %>
   <% if @item.favorited_by?(current_customer) %>
   <td><%= link_to item_favorites_path(@item), method: :delete do %>
    ♥<%= @item.favorites.count %>いいね
   <% end %>
   </td>
   <% else %>
   <td><%= link_to item_favorites_path(@item), method: :post do %>
    ♡<%= @item.favorites.count %>いいね
   <% end %>
   </td>
  <% end %>
  <% end %>
 </div>
 <div class="new-post">
  <%= form_with(model:[@item,@post], local: true) do |f| %>
   <%= f.text_field :title %>
   <%= f.text_area :body, rows="5" %>
   <%= f.submit '投稿する', class:'btn btn-success' %>
  <% end %>
 </div>
</div>

app/views/items/_form.html.erb
 <%= form_with model: @item, local: true do |f| %>
 <table class= 'table'>
　<div class="form-group"> 
　 <tr>
　  <th>商品画像</th>
　   <td><%= f.attachment_field :image %></td>
　   <th></th>
　 </tr>
　 <tr>
　  <th>商品名</th>
　   <td><%= f.text_field :name %></td>
　  <th>JANコード</th>
　   <td><%= f.text_field :jan_code %></td>
　 </tr>
　 <tr>
　  <th>商品説明</th>
　   <td><%= f.text_area :describe %></td>
　  <th>ジャンル</th>
　   <td> <%= f.collection_select(:genre_id, @genres, :id, :name) %></td>
　 </tr>
  </div>
  </table>
　<div class="form-group">
　 <%= f.submit "商品登録", class:'btn btn-success' %>
　 <% end %>
  </div>

app/views/items/_index.html.erb
<table class='table table-hover table-inverse'>
 <thead>
  <tr>
    <th>商品画像</th>
    <th>商品名</th>
    <th>JANコード</th>
    <th>商品説明</th>
    <th>ジャンル</th>
    <th></th>
    </tr>
   </thead>
    <% @items.each do |item| %>
   <tbody>
     <tr>
      <td><%= attachment_image_tag item, :image, :fill, 100, 100, format: 'jpeg' %></td>
      <td><%= item.name %></td>
      <td><%= item.jan_code %></td>
      <td><%= item.describe %></td>
      <td><%= item.genre.name %></td>
      <td><%= link_to '商品詳細', item_path(item.id), class:'btn btn-primary' %></td>
     </tr>
    <% end %>
    <tr><td><%= paginate @items %></td></tr>
   </tbody>
  </table>

app/views/items/edit.html.erb
<%= render 'layouts/header' %>
<div class="container- px-8 px-sm-4">
 <div class='row'>
  <div class="col-md-10 mb-3">
　<h1>登録商品編集</h1>
　<%= form_with model: @item, local:true do |f| %>
 <table class='table table-hover table-inverse'>
  <thead>
   <tr>
    <th>商品画像</th>
    <th>商品名</th>
    <th>JANコード</th>
    <th>商品説明</th>
    <th>ジャンル</th>
    <th></th>
   </tr>
   </thead>
　 
　 <tbody>
　  <tr>
　   <td><%= f.attachment_field :image %></td>
　   <td><%= f.text_field :name %></td>
　   <td><%= f.text_field :jan_code %></td>
　   <td><%= f.text_field :describe %></td>
　   <td>
      <label class="radio_button">
      <%= f.collection_select(:genre_id, @genres, :id, :name) %>
     </label>
     </td>
    </tr>
   </tbody>
    <tr>
　   <td><%= f.submit "変更を保存する", class:'btn btn-success' %></td>
　  </tr>
　 </table>
　<% end %>
　</div>
 </div>
</div>
<%= render 'layouts/footer' %>
 

app/views/items/index.html.erb
<%= render 'layouts/header' %>
<div class="container- px-6 px-sm-0">
 <div class='row'>
   
  <div class='col-8 offset-1'>
   <h1>商品一覧(全<%= @items.all.count %>件)</h1>
    <%= render 'index', item: @item %>
  </div>
   <div class="mx-auto">
   <h2>商品登録</h2>
    <%= render 'form', items: @items %>
   </div>
   </div>
    <%= render 'layouts/footer' %>
 
</div>

app/views/items/show.html.erb
<%= render 'layouts/header' %>
<div class="container- px-8 px-sm-4">
 <div class='row'>
  <h1>商品詳細</h1>
 <table class='table table-hover table-inverse'>
  <thead>
    <tr>
    <th>商品画像</th>
    <th>商品名</th>
    <th>JANコード</th>
    <th>商品説明</th>
    <th>ジャンル</th>
    <th></th>
    <th></th>
    </tr>
   </thead>
   <tbody>
    <td><%= attachment_image_tag @item, :image, :fill, 100, 100, format: 'jpeg' %></td>
    <td><%= @item.name %></td>
    <td><%= @item.jan_code %></td>
    <td><%= @item.describe %></td>
    <td><%= @item.genre.name %></td>
   
    <td><%= link_to '商品情報を編集する', edit_item_path(@item), class:'btn btn-success'%></td>
    <td><%= link_to '商品情報を削除する',item_path(@item),method: :delete, "data-confirm" => "本当に削除しますか？", class:'btn btn-danger' %></td>
    </tbody>
   </table>
   <h4>この商品についてのコメント一覧</h4>
 <table class='table table-hover table-inverse'>
   <thead>
    <th>投稿者</th>
    <th>投稿文</th>
    <th>いいね</th>
    <th></th>
   </thead>
   <tbody>
   <% @item.post.each do |post| %>
   <tr>
    <td><%#= @customers.last_name %><%#= @customers.first_name %></td>
    <td><%= post.body %></td>
    
    <%#= いいね機能 %>
    <td><%= render partial: 'favorites/favorite', locals: { post: post} %></td>
   
    <% if post.user == current_user %>
    <td><%= link_to "削除", item_post_path(post.item, post), method: :delete, "data-confirm" => "本当に削除しますか？", class:'btn btn-danger' %></td>
    <% end %>
   </tr>
   <% end %>
   </tbody>
   </table>
   
   <div class="mx-auto">
    <br><br>
   <h4>コメント新規投稿</h4>
   <%= form_with(model:[@item,@post], local: true) do |f| %>
   <table class= 'table'>
    <th>投稿文</th>
    <td><%= f.text_area :body, size: "80x5", autofocus: true, id:"inputName", placeholder:"最大80文字まで" %></td>
    <td><%= f.submit '投稿する', class:'btn btn-success' %></td>
   </table>
  <% end %>
  </div>
 </div>
    <%= render 'layouts/footer' %>
</div>

app/views/posts/post_comment.js.erb
$("#comments_area").html("<%= j(render 'items/item_comments', item: @item, post: @post) %>");

$("textarea").val('');