config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #devise_for :customers
  root to: 'homes#top'
  get '/search', to: 'searchs#search'
  
  resources :customers, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :items, only: [:index, :show, :create, :edit, :update, :destroy] do
   resources :posts, only: [:create, :destroy] do
     resource :favorites, only: [:create, :destroy]
   end
  end
  resources :genres, only: [:index, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attachment :image
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  
  attachment :image
  belongs_to :genre, optional: true
  has_many :post, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :item
  belongs_to :user
  validates :body, presence: true, length: {maximum: 80}
   has_many :favorites, dependent: :destroy
  
  def favorited_by?(current_user, post_id)
   favorites.where(post_id: post_id,user_id: current_user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :post, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @genres =  Genre.all
    @genres = Genre.page(params[:page]).per(5)
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
    redirect_to genres_path
    else
     render 'index'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
     redirect_to genres_path
    else
     render 'edit'
    end
  end
  
  def destroy
    @genres = Genre.find(params[:id])
    @genres.destroy
    redirect_to genres_path
  end
  
  private
 def genre_params
  params.require(:genre).permit(:name)
 end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @items = Item.all
    @items = Item.page(params[:page]).per(5)
    @item = Item.new 
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])
    #@customers = Customer.find(params[:id])
    @post = Post.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
     redirect_to item_path(@item), notice: "投稿成功しました"
    else
     @items = Item.all
     render 'index'
    end
  end
  
  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to item_path
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end
  
  private
   def item_params
    params.require(:item).permit(:name, :describe, :jan_code, :image, :genre_id)
   end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def create
    item = Item.find(params[:item_id])
    comment = current_user.post.new(post_params)
    comment.item_id = item.id
    comment.save
    redirect_to item_path(item)
  end  

  def destroy
    Post.find_by(id: params[:id], item_id: params[:item_id]).destroy
    redirect_to item_path(params[:item_id])
  end
  
 private
 def post_params
  params.require(:post).permit(:body)
 end
 
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
 
  def search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    @records = search_for(@model, @content, @method)
  end

private
 def search_for(model, content, method)
   if model == 'item'
    if method == 'perfect'
     Item.where(name: content)
    else
     Item.where('name LIKE ?', '%'+content+'%')
    end
   elsif model == 'genre'
     if method == 'perfect'
      Genre.where(name: content)
     else
      Genre.where('name LIKE ?', '%'+content+'%')
     end
   end
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/layouts/_footer.html.erb
<footer>
   <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight evaluation foods.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.htme.erb
<header>
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
   <a class="navbar-brand" href="/"><span>Bookers</span></a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
     <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
       <li><%= link_to 'Home', customer_path(current_user),class: 'fas fa-home nav-link text-light' %></li>
       <li><%= link_to 'customers', customers_path,class: 'fas fa-users nav-link text-light' %></li>
       <li><%= link_to 'items', items_path,class: 'fas fa-item nav-link text-light' %></li>
       <li><%= link_to 'logout', destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-light' %></li>
      <% else %>
       <td><%= render 'searchs/form' %></td>
       <li><%= link_to 'Home', root_path,class: 'fas fa-home nav-link text-light' %></li>
       <li><%= link_to 'signup', new_user_registration_path,class: 'fas fa-user-plus nav-link text-light' %></li>
       <li><%= link_to 'login', new_user_session_path ,class: 'fas fa-sign-in-alt nav-link text-light'%></li>
      <% end %>
    </ul>
  </div>
 </nav>
 
 </div>
</header>

app/views/layouts/_header.html.erb
<header>
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
   <a class="navbar-brand" href="/"><h4>evaluation foods</h4></a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
     <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
       <li><%= link_to 'customers', customers_path,class: 'fas fa-users nav-link text-light' %></li>
       <li><%= link_to 'items', items_path,class: 'fas fa-box nav-link text-light' %></li>
       <li><%= link_to 'genres', genres_path,class: 'fas fa-copy nav-link text-light' %></li>
       <li><%= link_to 'logout', destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-light' %></li>
       <span><%= render 'searchs/form' %></span>
      <% else %>
       <td><%= render 'searchs/form' %></td>
       <li><%= link_to 'Home', root_path,class: 'fas fa-home nav-link text-light' %></li>
       <li><%= link_to 'signup', new_user_registration_path,class: 'fas fa-user-plus nav-link text-light' %></li>
       <li><%= link_to 'login', new_user_session_path ,class: 'fas fa-sign-in-alt nav-link text-light'%></li>
      <% end %>
    </ul>
    
  </div>
 </nav>
 
 </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evaluation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>